const KUSAMA_RPC_PROVIDERS = ["wss://kusama-rpc.polkadot.io"];
const POLKADOT_RPC_PROVIDERS = ["wss://rpc.polkadot.io"];

const POLKADOT_DECIMALS = 10;
const KUSAMA_DECIMALS = 12;

const POLKADOT_MIN_BOND = 5000;
const KUSAMA_MIN_BOND = 10;

const POLKADOT_MAX_COMMISSION = 5;
const KUSAMA_MAX_COMMISSION = 15;

module.exports = {
    KUSAMA_RPC_PROVIDERS,
    POLKADOT_RPC_PROVIDERS,
    POLKADOT_DECIMALS,
    KUSAMA_DECIMALS,
    POLKADOT_MIN_BOND,
    KUSAMA_MIN_BOND,
    POLKADOT_MAX_COMMISSION,
    KUSAMA_MAX_COMMISSION
}